package main

var attributesFileTemplate = `// Code generated by cmd/generate; DO NOT EDIT.
package attr 

{{range . -}}
func {{ .FuncName }}(value any) Attributes {
	return Attributes{AttrPair{Key: "{{ .AttrName }}", Value: value}}
}
func (a Attributes) {{ .FuncName }}(value any) Attributes {
	return append(a, AttrPair{Key: "{{ .AttrName }}", Value: value})
}
{{ end }}`

var elementsFileTemplate = `// Code generated by cmd/generate. DO NOT EDIT.
package html

import "github.com/mbertschler/html/attr"

{{range . -}}
{{ if .NoChildren -}}
func {{ .FuncName }}(attr attr.Attributes) Block {
	return newElement("{{ .TagName }}", attr, nil, Void)
}
{{ else -}}
func {{ .FuncName }}(attr attr.Attributes, children ...Block) Block {
	return newElement("{{ .TagName }}", attr, children, {{ .Option }})
}
{{ end }}{{ end }}`
